insert into APP_VERSION(oid, APP_OID, VERSION, CODE, description, DEPLOY_FILE_NAME, SEQ, CONTEXT_PATH, valid, insert_time)
    values('00001', '00001', '0.1','Tiger', 'First test version', 'E:/work/xthinker/B-Cloud/workspace/appAndResourceMgr/deployPackages/00001/tiger.0.1.war', 0, '/', 'y', now());
	
	
insert into APP_VERSION(oid, APP_OID, VERSION, CODE, description, DEPLOY_FILE_NAME, SEQ, CONTEXT_PATH, valid, insert_time)
    values('00002', '00002', '0.1','Dolphin', 'Alpha version', 'E:/work/xthinker/B-Cloud/workspace/appAndResourceMgr/deployPackages/00002/dolphin.0.1.war', 0, '/', 'y', now());