insert into app_host (OID, APP_OID, HOST, VALID)
        values('1', '00001', 'www.bc_demo1.com', 'y');

insert into app_host (OID, APP_OID, HOST, VALID)
        values('2', '00001', 'rcp.bc_demo1.com', 'y');

insert into app_host (OID, APP_OID, HOST, VALID)
        values('3', '00002', 'www.bc_demo1.com', 'y');
		
insert into app_host (OID, APP_OID, HOST, VALID)
        values('6', '00001', '/sec', 'y');

