# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("LoadRunner.Global.DontPromptOnEnter", false);
user_pref("LoadRunner.Global.ShowAnimations", true);
user_pref("LoadRunner.Global.ShowLineNumbers", true);
user_pref("LoadRunner.Global.SidebarOnLeft", true);
user_pref("LoadRunner.Global.SidebarWidth", 350);
user_pref("LoadRunner.Global.ToolboxY", 0);
user_pref("LoadRunner.RTS.iteration_number", 0);
user_pref("LoadRunner.config.output_dir", "E:\\work\\xthinker\\B-Cloud\\performance\\Home-Test\\");
user_pref("LoadRunner.config.root_dir", "D:\\Program Files\\HP\\LoadRunner");
user_pref("LoadRunner.config.runlogic_path", "E:\\work\\xthinker\\B-Cloud\\performance\\Home-Test\\\\default.usp");
user_pref("LoadRunner.config.user_dir", "E:\\work\\xthinker\\B-Cloud\\performance\\Home-Test");
user_pref("LoadRunner.sidebar.lock", true);
user_pref("accessibility.blockautorefresh", true);
user_pref("accessibility.disableenumvariant", true);
user_pref("accessibility.warn_on_browsewithcaret", false);
user_pref("advanced.system.supportDDEExec", false);
user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1339724513);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1339724380);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.download.manager.addToRecentDocs", false);
user_pref("browser.download.manager.quitBehavior", 2);
user_pref("browser.download.manager.scanWhenDone", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.microsummary.enabled", false);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.popups.showPopupBlocker", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.privatebrowsing.dont_prompt_on_enter", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.safebrowsing.remoteLookups", false);
user_pref("browser.search.log", false);
user_pref("browser.search.suggest.enabled", false);
user_pref("browser.search.update", false);
user_pref("browser.search.updateinterval", -1);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.max_resumed_crashes", 0);
user_pref("browser.sessionstore.max_tabs_undo", 0);
user_pref("browser.sessionstore.max_windows_undo", 0);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.tabs.loadOnNewTab", 0);
user_pref("browser.warnOnClose", false);
user_pref("browser.warnOnOpen", false);
user_pref("browser.warnOnQuit", false);
user_pref("browser.windows.loadOnNewWindow", 0);
user_pref("browser.xul.error_pages.enabled", true);
user_pref("config.trim_on_minimize", false);
user_pref("dom.max_chrome_script_run_time", 60);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.enabledItems", "TruClient@hp.com:11.00,fiddlerhook@fiddler2.com:2.3.9.1,{97E22097-9A2F-45b1-8DAF-36AD648C7EF4}:15.0.4,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.3");
user_pref("extensions.lastAppVersion", "3.6.3");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("general.useragent.extra.firefox", "Firefox/3.6.3");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("javascript.options.showInConsole", true);
user_pref("layout.css.report_errors", false);
user_pref("layout.spellcheckDefault", 0);
user_pref("metrics.upload.enable", false);
user_pref("microsoft.CLR.auto_install", false);
user_pref("network.automatic-ntlm-auth.allow-proxies", false);
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.dnsCacheExpiration", 3600);
user_pref("network.http.phishy-userpass-length", 255);
user_pref("network.manage-offline-status", false);
user_pref("network.prefetch-next", false);
user_pref("network.protocol-handler.external-default", false);
user_pref("network.protocol-handler.external.mailto", false);
user_pref("network.protocol-handler.external.news", false);
user_pref("network.protocol-handler.external.nntp", false);
user_pref("network.protocol-handler.external.snews", false);
user_pref("network.protocol-handler.warn-external-default", false);
user_pref("network.protocol-handler.warn-external.afp", false);
user_pref("network.protocol-handler.warn-external.data", false);
user_pref("network.protocol-handler.warn-external.disk", false);
user_pref("network.protocol-handler.warn-external.disks", false);
user_pref("network.protocol-handler.warn-external.hcp", false);
user_pref("network.protocol-handler.warn-external.javascript", false);
user_pref("network.protocol-handler.warn-external.mailto", false);
user_pref("network.protocol-handler.warn-external.moz-icon", false);
user_pref("network.protocol-handler.warn-external.ms-help", false);
user_pref("network.protocol-handler.warn-external.news", false);
user_pref("network.protocol-handler.warn-external.nntp", false);
user_pref("network.protocol-handler.warn-external.shell", false);
user_pref("network.protocol-handler.warn-external.snews", false);
user_pref("network.protocol-handler.warn-external.vbscript", false);
user_pref("network.protocol-handler.warn-external.vnd.ms.radio", false);
user_pref("plugin.default_plugin_disabled", false);
user_pref("plugins.hide_infobar_for_missing_plugin", true);
user_pref("privacy.popups.policy", 1);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.autofillForms", false);
user_pref("signon.prefillForms", false);
